import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Infinite Scrolling</title>
        <meta
          name="infinite-scrolling"
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Infinite Scrolling</h1>
        <input
          className={styles.input}
          placeholder="search a book"
          type="text"
        />
        <div>Title</div>
        <div>Title</div>
        <div>Title</div>
        <div>Loading ...</div>
        <div>Error</div>
      </main>
    </>
  );
}
